In [23]:
import zarrtraj
import MDAnalysis as mda
from MDAnalysisTests.datafiles import PSF
import zarr
import numpy as np
import os
import h5py


u = mda.Universe(PSF, 'zarr_3341_100.zarrtraj')

for ts in u.trajectory:
    print(ts[0])


[5805.  601. 4015.]
[11610.  1202.  8030.]
[23220.  2404. 16060.]
[46440.  4808. 32120.]
[92880.  9616. 64240.]
[185760.  19232. 128480.]
[371520.  38464. 256960.]
[743040.  76928. 513920.]
[1486080.  153856. 1027840.]
[2972160.  307712. 2055680.]
[5944320.  615424. 4111360.]
[11888640.  1230848.  8222720.]
[23777280.  2461696. 16445440.]
[47554560.  4923392. 32890880.]
[95109120.  9846784. 65781760.]
[1.9021824e+08 1.9693568e+07 1.3156352e+08]
[3.8043648e+08 3.9387136e+07 2.6312704e+08]
[7.6087296e+08 7.8774272e+07 5.2625408e+08]
[1.52174592e+09 1.57548544e+08 1.05250816e+09]
[3.0434918e+09 3.1509709e+08 2.1050163e+09]
[6.0869837e+09 6.3019418e+08 4.2100326e+09]
[1.2173967e+10 1.2603884e+09 8.4200653e+09]
[2.4347935e+10 2.5207767e+09 1.6840131e+10]
[4.8695869e+10 5.0415534e+09 3.3680261e+10]
[9.7391739e+10 1.0083107e+10 6.7360522e+10]
[1.94783478e+11 2.01662136e+10 1.34721044e+11]
[3.8956696e+11 4.0332427e+10 2.6944209e+11]
[7.7913391e+11 8.0664855e+10 5.3888418e+11]
[1.55826782e+12 1

In [31]:
import fsspec
import s3fs
import zarr


s3 = s3fs.S3FileSystem(key='AKIAUODTGZQXMD5QNMP5', 
    secret='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',
)


store = s3fs.S3Map(root='s3://test-zarrtraj-bucket/zarr_3341_100.zarrtraj', s3=s3, check=False)
root = zarr.open_group(, mode='r')

isinstance(root, zarr.Group)
u = mda.Universe(PSF, root, format="ZARRTRAJ")

#for ts in u.trajectory:
#    print(ts[0])


TypeError: Unable to read particles with <class 'zarrtraj.ZARRTRAJ.ZarrTrajReader'>.

In [ ]:
u = mda.Universe(PSF, 's3://test-zarrtraj-bucket/zarr_3341_100.zarrtraj', storage_options={'key':'AKIAUODTGZQXMD5QNMP5', 'secret':'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'})

In [35]:


root = zarr.open_group('s3://test-zarrtraj-bucket/zarr_3341_100.zarrtraj', mode='r',storage_options={'key':'AKIAUODTGZQXMD5QNMP5', 'secret':'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'})
root.tree()

Tree(nodes=(Node(disabled=True, name='/', nodes=(Node(disabled=True, name='particles', nodes=(Node(disabled=Tr…

In [36]:
u = mda.Universe(PSF, root)

for ts in u.trajectory:
    print(ts)

NameError: name 'mda' is not defined